#!/usr/bin/env python3
"""
AI-MASTERY-COURSE: Daily AI News and Trend Update
Lee noticias, blogs y señales de tendencia para mantener actualizado el curso.
"""

import os
import json
import logging
from datetime import datetime, date
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
LOG_DIR = BASE_DIR / "logs"
UPDATE_DIR = BASE_DIR / "updates" / "daily"
RESEARCH_DIR = BASE_DIR / "research"
MEMORY_DIR = BASE_DIR / "memory"

for d in [LOG_DIR, UPDATE_DIR, RESEARCH_DIR, MEMORY_DIR]:
    d.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "news_update.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# RSS feeds to monitor
RSS_FEEDS = {
    "arXiv cs.AI": "https://arxiv.org/rss/cs.AI",
    "arXiv cs.LG": "https://arxiv.org/rss/cs.LG",
    "arXiv cs.CL": "https://arxiv.org/rss/cs.CL",
    "Hugging Face": "https://huggingface.co/blog/feed.xml",
    "OpenAI Blog": "https://openai.com/blog/rss.xml",
    "Google AI Blog": "https://blog.google/technology/ai/rss/",
    "Anthropic Blog": "https://www.anthropic.com/rss.xml",
    "DeepMind Blog": "https://www.deepmind.com/blog/rss.xml",
}

def get_today():
    return date.today().isoformat()

def load_json(path, default=None):
    if default is None:
        default = {}
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return default

def save_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def try_fetch_rss(name, url):
    """Try to fetch an RSS feed, return empty list on failure"""
    try:
        import feedparser
        feed = feedparser.parse(url)
        entries = []
        for entry in feed.entries[:5]:
            entries.append({
                "title": entry.get("title", ""),
                "link": entry.get("link", ""),
                "published": entry.get("published", ""),
                "summary": entry.get("summary", "")[:200]
            })
        logger.info(f"Fetched {len(entries)} entries from {name}")
        return entries
    except Exception as e:
        logger.warning(f"Failed to fetch {name}: {e}")
        return []

def generate_news_report():
    """Generate the daily news report"""
    today = get_today()
    report_path = UPDATE_DIR / f"{today}-ai-news.md"
    
    all_entries = {}
    for name, url in RSS_FEEDS.items():
        entries = try_fetch_rss(name, url)
        if entries:
            all_entries[name] = entries
    
    report = f"""# AI News Update - {today}

## Summary
Automated news scan completed. Sources: {len(RSS_FEEDS)} feeds monitored.

## Latest News by Source

"""
    
    for source, entries in all_entries.items():
        report += f"### {source}\n\n"
        for entry in entries:
            report += f"- [{entry['title']}]({entry['link']})\n"
            if entry.get("summary"):
                report += f"  {entry['summary']}\n"
        report += "\n"
    
    if not all_entries:
        report += "No entries fetched. This may be due to network issues.\n"
        report += "The feeds are configured and will work when network is available.\n\n"
    
    report += f"""
## Trend Watch
- Monitor arXiv for new papers in cs.AI, cs.LG, cs.CL
- Check Hugging Face for new models and datasets
- Review OpenAI/Anthropic/DeepMind blogs for announcements

## What Changed in AI
See [course/28-frontier-research/what-changed-recently.md](../course/28-frontier-research/what-changed-recently.md)

---
Generated by daily_news_update.py at {datetime.now().isoformat()}
"""
    
    with open(report_path, "w") as f:
        f.write(report)
    
    logger.info(f"News report saved to {report_path}")
    return report_path

def update_trend_watch():
    """Update the trend watch file"""
    today = get_today()
    trend_path = RESEARCH_DIR / "trend-watch.md"
    
    trends = [
        "Agentic AI and autonomous agents",
        "Multimodal models (text + image + audio + video)",
        "Open-source LLMs competitive with proprietary",
        "Efficient inference (quantization, distillation, pruning)",
        "RAG and knowledge-augmented generation",
        "AI safety and alignment research",
        "Regulation (AI Act, executive orders)",
        "MCP (Model Context Protocol) for tool use",
        "Mixture of Experts architectures",
        "Long-context models (1M+ tokens)",
    ]
    
    content = f"""# Trend Watch

Last updated: {today}

## Current Trends

{chr(10).join(f"- {t}" for t in trends)}

## Monitoring
This file is updated daily by automation/daily_news_update.py

## Sources
- arXiv, Hugging Face, OpenAI, Anthropic, DeepMind, Google AI
"""
    
    with open(trend_path, "w") as f:
        f.write(content)
    
    logger.info("Trend watch updated")

def update_history():
    """Update the update history"""
    history_path = MEMORY_DIR / "update-history.json"
    history = load_json(history_path, {"updates": []})
    
    history["updates"].append({
        "date": get_today(),
        "type": "news_update",
        "status": "completed",
        "sources_monitored": len(RSS_FEEDS)
    })
    
    # Keep last 365 entries
    history["updates"] = history["updates"][-365:]
    save_json(history_path, history)
    logger.info("Update history saved")

def main(commit=False, push=False):
    logger.info("=" * 60)
    logger.info("Starting Daily AI News Update")
    logger.info("=" * 60)
    
    report_path = generate_news_report()
    update_trend_watch()
    update_history()
    
    logger.info("News update complete")
    
    if commit:
        import subprocess
        subprocess.run(["git", "add", "."], cwd=BASE_DIR)
        subprocess.run(["git", "commit", "-m", f"📰 News update {get_today()}"], cwd=BASE_DIR)
        if push:
            subprocess.run(["git", "push"], cwd=BASE_DIR)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Daily AI News Update")
    parser.add_argument("--commit", action="store_true")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()
    main(commit=args.commit, push=args.push)
