#!/usr/bin/env python3
"""
AI-MASTERY-COURSE: Daily Knowledge Expansion Script
Busca nueva información educativa, técnica y académica para ampliar el curso.
"""

import os
import json
import logging
from datetime import datetime, date
from pathlib import Path

# Setup
BASE_DIR = Path(__file__).parent.parent
LOG_DIR = BASE_DIR / "logs"
UPDATE_DIR = BASE_DIR / "updates" / "daily"
RESEARCH_DIR = BASE_DIR / "research"
MEMORY_DIR = BASE_DIR / "memory"

LOG_DIR.mkdir(parents=True, exist_ok=True)
UPDATE_DIR.mkdir(parents=True, exist_ok=True)
RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
MEMORY_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "knowledge_expansion.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

def get_today():
    return date.today().isoformat()

def load_json(path, default=None):
    if default is None:
        default = {}
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return default

def save_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def collect_arxiv_topics():
    """Define topics to search on arXiv"""
    return [
        "cs.AI", "cs.LG", "cs.CL", "cs.CV", "cs.NE",
        "cs.RO", "stat.ML", "cs.MA"
    ]

def collect_github_topics():
    """Define topics to search on GitHub"""
    return [
        "large-language-model", "transformer", "diffusion-model",
        "reinforcement-learning", "multi-agent", "rag",
        "fine-tuning", "quantization", "mcp-server"
    ]

def generate_expansion_report():
    """Generate the daily knowledge expansion report"""
    today = get_today()
    report_path = UPDATE_DIR / f"{today}-knowledge-expansion.md"
    
    topics_arxiv = collect_arxiv_topics()
    topics_github = collect_github_topics()
    
    report = f"""# Knowledge Expansion Report - {today}

## Summary
Automated knowledge expansion scan completed.

## Topics Scanned

### arXiv Categories
{chr(10).join(f"- {t}" for t in topics_arxiv)}

### GitHub Topics
{chr(10).join(f"- {t}" for t in topics_github)}

## Recommendations
- Review new papers in cs.AI and cs.LG
- Check GitHub trending for LLM-related repos
- Update course modules with new findings
- Add new references to references/papers.md

## Next Steps
1. Run `python automation/daily_news_update.py`
2. Run `python automation/run_coverage_audit.py`
3. Review and merge changes

---
Generated by daily_knowledge_expansion.py at {datetime.now().isoformat()}
"""
    
    with open(report_path, "w") as f:
        f.write(report)
    
    logger.info(f"Expansion report saved to {report_path}")
    return report_path

def update_research_log():
    """Update the research log"""
    today = get_today()
    log_path = RESEARCH_DIR / "research-log.md"
    
    entry = f"""
## {today}
- Scanned arXiv categories: {', '.join(collect_arxiv_topics())}
- Scanned GitHub topics: { ', '.join(collect_github_topics())}
- Status: automated scan complete
"""
    
    if log_path.exists():
        with open(log_path) as f:
            existing = f.read()
    else:
        existing = "# Research Log\n\n"
    
    with open(log_path, "w") as f:
        f.write(existing + entry)
    
    logger.info("Research log updated")

def update_priority_queue():
    """Update the priority queue with new topics"""
    queue_path = MEMORY_DIR / "priority-queue.json"
    queue = load_json(queue_path, {"high": [], "medium": [], "low": [], "last_updated": ""})
    
    # Add new priorities based on scan
    new_priorities = [
        {"topic": "MCP (Model Context Protocol)", "priority": "high", "module": "16-ai-agents"},
        {"topic": "Mixture of Experts (MoE)", "priority": "high", "module": "12-large-language-models"},
        {"topic": "Vision Language Models", "priority": "high", "module": "17-multimodal-ai"},
        {"topic": "Constitutional AI", "priority": "medium", "module": "22-ai-safety-alignment-and-security"},
        {"topic": "State Space Models (Mamba)", "priority": "medium", "module": "28-frontier-research"},
    ]
    
    existing_topics = {p["topic"] for p in queue.get("high", []) + queue.get("medium", []) + queue.get("low", [])}
    
    for p in new_priorities:
        if p["topic"] not in existing_topics:
            queue.setdefault(p["priority"], []).append(p)
    
    queue["last_updated"] = get_today()
    save_json(queue_path, queue)
    logger.info("Priority queue updated")

def main(commit=False, push=False):
    logger.info("=" * 60)
    logger.info("Starting Daily Knowledge Expansion")
    logger.info("=" * 60)
    
    report_path = generate_expansion_report()
    update_research_log()
    update_priority_queue()
    
    logger.info("Knowledge expansion complete")
    logger.info(f"Report: {report_path}")
    
    if commit:
        import subprocess
        subprocess.run(["git", "add", "."], cwd=BASE_DIR)
        subprocess.run(["git", "commit", "-m", f"📚 Knowledge expansion {get_today()}"], cwd=BASE_DIR)
        if push:
            subprocess.run(["git", "push"], cwd=BASE_DIR)
            logger.info("Changes pushed")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Daily Knowledge Expansion")
    parser.add_argument("--commit", action="store_true", help="Commit changes")
    parser.add_argument("--push", action="store_true", help="Push changes")
    args = parser.parse_args()
    main(commit=args.commit, push=args.push)
